version: '3'
services:
  nrf:
    image: fw-nrfconnect-nrf-docker:nrfutil
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ..:/workdir/project
      # Make the bash prompt beautiful
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    tmpfs:
      - /tmp
    environment:
      - HOME=/tmp
    working_dir: /workdir/project/application
